### ISSUE TITLE
What to enter for sha256 field?

### ISSUE THREAD

**Issue by lane-s** [mjbots/rpi_bazel#1]
I'm sure this is a stupid question, but I can't seem to figure it out:
What should I replace the X's with for the line `sha256 = "XXX"` in `repository.bzl`?
I'm assuming you would fill in the commit hash for the first line i.e. `commit = "6079a21"` , but I'm not sure about the next one. I tried the longer hash (`sha256 = "6079a215f431c8f1b86c2b315fb2ab7e410b64b4"`), but when attempting to build I got `Invalid SHA256 checksum`. 

I'm hoping that this repo may be able to help me build [envoy](https://github.com/envoyproxy/envoy/) so that I can run a gRPC backend on my pi and communicate with it from a web interface, but I'm in pretty over my head trying to deal with these complex build processes. Anyway, thanks for creating this repo- even if it can't help in my particular case I'm sure it will be really useful for getting other C++ code running on raspberry pi.

**Comment by jpieper** [comment]
You just put in what bazel tells you it expected. If you leave the line commented out, bazel prints the desired as all zeros which makes it easy to figure out which is which. 

Try that and see if you can get unstuck?

**Comment by lane-s** [comment]
Thanks, that allowed me to move forward. I'm still unable to build the project, but I'll make a new issue for that.

**Comment by AkshayChoulwar** [comment]
@jpieper Sorry to raise the question here, While trying your readme instructions I am getting this error,

ERROR: /Documents/rpi_bazel/tools/workspace/raspberry_pi/repository.bzl:57:1: Variable raspberry_pi_repository is read only
Need help? See https://bazel.build/versions/master/docs/skylark/errors/read-only-variable.html
ERROR: error loading package '': in /Users/akshaychoulwar/Documents/rpi_bazel/tools/workspace/default.bzl: Extension 'tools/workspace/raspberry_pi/repository.bzl' has errors

command used: bazel build --config=pi //...

**Comment by jpieper** [comment]
@AkshayChoulwar sorry, am travelling.  Want to first check what version of bazel you are using, and open a new issue if you have a problem with 0.26.1?
