### ISSUE TITLE
"C compiler cannot create executables" when trying to cross compile a simple library built with CMake

### ISSUE THREAD

**Issue by henriksod** [mjbots/rpi_bazel#10]
I am getting `C compiler cannot create executables` error when trying to cross compile a simple [library built with CMake](https://github.com/the-tcpdump-group/libpcap) using this repo.

```bazel
# .bazelrc
build:pi --crosstool_top=@rpi_bazel//tools/cc_toolchain:toolchain
build:pi --cpu=aarch64
build:pi --compiler=clang
```

```bazel
# WORKSPACE

# ...

http_archive(
    name = "rpi_bazel",
    url = "https://github.com/mjbots/rpi_bazel/archive/964b6feb8bb14b2a58876b406f17266538794c3a.zip",
    sha256 = "ef22526864f46d4bc42b09b421050697ebc1970f279f196b8f855048df6f3e3e",
    strip_prefix = "rpi_bazel-964b6feb8bb14b2a58876b406f17266538794c3a",
)

load("@rpi_bazel//tools/workspace:default.bzl",
    rpi_bazel_deps = "add_default_repositories")
rpi_bazel_deps()

# ...

http_archive(
    name = "com_github_the_tcpdump_group_libpcap",
    build_file = "//:bazel/cpp/libpcap/BUILD.libpcap.bzl",
    # Here you can use e.g. sha256sum cli utility to compute the sha sum.
    sha256 = "1783ff39f2a6eb99a7625c7ea471782614c94965ea934b6b22ac6eb38db266bc",
    strip_prefix = "libpcap-libpcap-1.10.4",
    url = "https://github.com/the-tcpdump-group/libpcap/archive/refs/tags/libpcap-1.10.4.tar.gz",
)
```

```bazel
# bazel/cpp/libpcap/BUILD.libpcap.bzl

load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
)

cmake(
    name = "libpcap",
    cache_entries = {
        "CMAKE_C_FLAGS": "-fPIC",
    },
    lib_source = ":all_srcs",
    out_shared_libs = ["libpcap.so"],
    visibility = ["//visibility:public"],
)
```

Running:

`bazel build --config=pi @com_github_the_tcpdump_group_libpcap//:libpcap`

I get this output from rules_foreign_cc:

```bash
_____ BEGIN BUILD LOGS _____
+ AR=/home/henrik/.cache/bazel/.../external/rpi_bazel/tools/cc_toolchain/wrapper/clang-ar
+ ARFLAGS=rcsD
+ CC=/home/henrik/.cache/bazel/.../external/rpi_bazel/tools/cc_toolchain/wrapper/clang-clang
+ CFLAGS='-nostdinc++ -isystem /home/henrik/.cache/bazel/.../external/org_llvm_libcxx/include -isystem /home/henrik/.cache/bazel/.../external/org_llvm_libcxxabi/include -Wno-builtin-macro-redefined -D__DATE__=redacted -D__TIMESTAMP__=redacted -D__TIME__=redacted -fPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -DNDEBUG -O2 -ffunction-sections -fdata-sections -fno-limit-debug-info -g0'
+ LD=/home/henrik/.cache/bazel/.../external/rpi_bazel/tools/cc_toolchain/wrapper/clang-clang
+ LDFLAGS='-lm -lpthread -ldl -lrt -Wl,-no-as-needed -pie -Wl,-z,relro,-z,now -Wl,--build-id=md5 -Wl,--hash-style=gnu -no-canonical-prefixes -B -Wl,--gc-sections -fuse-ld=lld -fno-limit-debug-info'
+ ./configure --without-guile --with-guile=no --disable-dependency-tracking --prefix=/home/henrik/.cache/bazel/.../bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/make
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... /home/henrik/.cache/bazel/.../external/rpi_bazel/tools/cc_toolchain/wrapper/clang-clang
checking whether the C compiler works... no
configure: error: in `/home/henrik/.cache/bazel/.../bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/make.build_tmpdir':
configure: error: C compiler cannot create executables
See `config.log' for more details
_____ END BUILD LOGS _____
```

Is there a way to use system cmake instead?

**Comment by jpieper** [comment]
Unfortunately rpi_bazel is not compatible with `foreign_cc`.  To use rpi_bazel, you'll need to manually replicate the build system into bazel.  I don't have an example for libpcap, but you can find many other examples at https://github.com/mjbots/bazel_deps/tree/master/tools/workspace and a short writeup of how to do it for autoconf based packages here: https://jpieper.com/2018/12/09/bazel-ifying-simple-autoconf-packages/

**Comment by henriksod** [comment]
I am actually trying to cross compile a ROS2 node using [rules_ros2](https://github.com/mvukov/rules_ros2) and it is failing when trying to compile cyclonedds since that requires to be compiled via CMake.

This was just a simple example that I tried to make sure nothing else was wrong ☺️

Is there no way to sort out compatibility? Why does this repo need a specific clang version?

**Comment by jpieper** [comment]
Not really, you would need to take an entirely different implementation approach to allow foreign_cc to work, and I'm not even sure such a thing would be possible even with large amounts of effort.

I don't think the clang version is your problem here.

**Comment by jpieper** [comment]
In short, this repo can only be used with things that have a bazel build system.  As the bazel_deps repo shows, it often is not hard to write a minimal working bazel build system for arbitrary things, but in some cases it can be a lot of work.

**Comment by henriksod** [comment]
Alright, I will investigate that further then.

Thanks!

**Comment by henriksod** [comment]
Update: I managed to cross compile towards armv7 using the following [gcc toolchain repo](https://github.com/aspect-build/gcc-toolchain). Worked with `foreign_cc` as well. The compiled executable runs on my raspberry pi 4 model b.

[See this issue for reference](https://github.com/bazelbuild/rules_foreign_cc/issues/869)

**Comment by henriksod** [comment]
Closed as it was resolved using https://github.com/aspect-build/gcc-toolchain
