### ISSUE TITLE
external/org_llvm_libcxx/include/__config:219:12: fatal error: 'features.h' file not found

### ISSUE THREAD

**Issue by cjds** [mjbots/rpi_bazel#4]
Hello,

When I try to use this library

```
INFO: Build option --compiler has changed, discarding analysis cache.
INFO: Analyzed 5 targets (0 packages loaded, 3459 targets configured).
INFO: Found 5 targets...
ERROR: /rpicar/platform/BUILD:1:1: C++ compilation of rule '//platform:platform' failed (Exit 1) clang-clang failed: error executing command external/rpi_bazel/tools/cc_toolchain/wrapper/clang-clang -MD -MF bazel-out/armeabihf-fastbuild/bin/platform/_objs/platform/main.pic.d ... (remaining 34 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from platform/src/main.cc:5:
In file included from ./platform/include/rpi_gpio.h:6:
In file included from ./holster/include/error.h:9:
In file included from external/org_llvm_libcxx/include/optional:149:
external/org_llvm_libcxx/include/__config:219:12: fatal error: 'features.h' file not found
#  include <features.h>
           ^~~~~~~~~~~~
1 error generated.
INFO: Elapsed time: 0.905s, Critical Path: 0.52s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

The above code happens. `features.h` is present on the system however
```
root@cjds:/# find . -name features.h
./usr/include/features.h
./usr/include/c++/8/parallel/features.h
./usr/include/c++/9/parallel/features.h
./usr/include/c++/10/parallel/features.h
./usr/arm-linux-gnueabi/include/features.h
./usr/arm-linux-gnueabi/include/c++/9/parallel/features.h
./root/.cache/bazel/_bazel_root/a24326a56432a033218a21510efea07d/external/raspberry_pi/sysroot/usr/include/features.h
./root/.cache/bazel/_bazel_root/a24326a56432a033218a21510efea07d/external/raspberry_pi/sysroot/usr/include/c++/6.3.0/parallel/features.h
./root/.cache/bazel/_bazel_root/a24326a56432a033218a21510efea07d/external/raspberry_pi/sysroot/usr/include/c++/6/parallel/features.h
```

I'm using clang-10 in Docker of Ubuntu 18.04

**Comment by jpieper** [comment]
1) rpi_bazel is only intended to work with the clang configured in the repo which is currently clang 9.  That looks like what you're likely actually using.

2) Could you post a public repo which reproduces the problem?  It may be an interaction with docker of some kind.

**Comment by cjds** [comment]
1. I'm actually trying to use Clang 10
2, Here's a link with examples of how to build https://github.com/cjds/rpicar/pull/1/files

**Comment by jpieper** [comment]
I think that repository must be private?  I cannot access it.

**Comment by cjds** [comment]
You're right. Just flipped it. My mistake

**Comment by jpieper** [comment]
Unfortunately, that won't help me reproduce, since you just call out a `native_repository` for rpi_bazel.  Mind pushing a fork with your draft changes there too?

**Comment by cjds** [comment]
So technically there is no `native_repository` . I just switched from `http_repository` to try to make the required changes myself but got pretty lost and figured `features.h` seems more like a system level thing.

My "native_repository" is just a clone of this repository on this commit 65e9ae275849108b0fce7328d91e7c24b39f28c2

P.S. I really appreciate the effort you are putting in

**Comment by jpieper** [comment]
OK.  So to clarify, you got the error after trying to switch the repository to use clang 10 locally?

**Comment by cjds** [comment]
Oh I think this is my misunderstanding of how this works.

I'm agnostic to which clang I use.

But I have clang-10 installed locally.

My understanding is that this used the system clang but if the clang is contained within the toolchain , that's my mistake.

I did not make any changes to the local repository at all

**Comment by jpieper** [comment]
Yes, rpi_bazel downloads and uses a specific version of clang, currently 9.0.  You do not need clang installed locally at all.  Let me test your repo with an unmodified version of rpi_bazel and I'll report back.

**Comment by jpieper** [comment]
OK.  I didn't test using docker yet, but was able to build your software just fine locally with a few fixes for missing includes.  Also, the c++ standard library has to be manually added as a link time dependency for binaries. :(  I tested with bazel 1.2.0 and bazel 3.0.0 using:

```
tools/bazel build --config=pi //platform:platform
```

https://github.com/jpieper/rpicar/commits/rpi_bazel

**Comment by jpieper** [comment]
It doesn't look like your docker config is setup for anyone else to get your images, so I can't test in that specific environment.  If you are still stuck, let me know and I can try from there.

**Comment by cjds** [comment]
I uploaded the docker to `cjds/rpicar` so you can pull using 

```
docker pull cjds/rpicar
```

I built a fresh docker to double check if the compile works and this is what happened

First `libtinfo5` doesn't exist so I install it via `apt install libtinfo5` then the `features.h` error reoccurs


```
INFO: Analyzed 5 targets (22 packages loaded, 3543 targets configured).
INFO: Found 5 targets...
ERROR: /root/.cache/bazel/_bazel_root/a24326a56432a033218a21510efea07d/external/org_llvm_libcxxabi/BUILD.bazel:24:1: C++ compilation of rule '@org_llvm_libcxxabi//:libcxxabi' failed (Exit 127) clang-clang failed: error executing command external/rpi_bazel/tools/cc_toolchain/wrapper/clang-clang -MD -MF bazel-out/armeabihf-fastbuild/bin/external/org_llvm_libcxxabi/_objs/libcxxabi/cxa_guard.pic.d ... (remaining 42 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/org_llvm_clang/bin/clang: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
INFO: Elapsed time: 93.535s, Critical Path: 0.59s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
root@cjds:/rpicar# apt install libtinfo5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libtinfo5
0 upgraded, 1 newly installed, 0 to remove and 15 not upgraded.
Need to get 83.0 kB of archives.
After this operation, 535 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 libtinfo5 amd64 6.2-0ubuntu2 [83.0 kB]
Fetched 83.0 kB in 1s (77.3 kB/s)    
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libtinfo5:amd64.
(Reading database ... 22803 files and directories currently installed.)
Preparing to unpack .../libtinfo5_6.2-0ubuntu2_amd64.deb ...
Unpacking libtinfo5:amd64 (6.2-0ubuntu2) ...
Setting up libtinfo5:amd64 (6.2-0ubuntu2) ...
Processing triggers for libc-bin (2.31-0ubuntu6) ...
root@cjds:/rpicar# bazel build --config=pi //...
INFO: Analyzed 5 targets (0 packages loaded, 0 targets configured).
INFO: Found 5 targets...
ERROR: /root/.cache/bazel/_bazel_root/a24326a56432a033218a21510efea07d/external/org_llvm_libcxxabi/BUILD.bazel:24:1: C++ compilation of rule '@org_llvm_libcxxabi//:libcxxabi' failed (Exit 1) clang-clang failed: error executing command external/rpi_bazel/tools/cc_toolchain/wrapper/clang-clang -MD -MF bazel-out/armeabihf-fastbuild/bin/external/org_llvm_libcxxabi/_objs/libcxxabi/cxa_aux_runtime.pic.d ... (remaining 42 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/org_llvm_libcxxabi/src/cxa_aux_runtime.cpp:12:
In file included from external/org_llvm_libcxxabi/include/cxxabi.h:17:
In file included from external/org_llvm_libcxx/include/stddef.h:39:
external/org_llvm_libcxx/include/__config:219:12: fatal error: 'features.h' file not found
#  include <features.h>
           ^~~~~~~~~~~~
1 error generated.
INFO: Elapsed time: 0.682s, Critical Path: 0.51s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by jpieper** [comment]
Your problem is that you have bazel configured to use its sandbox from within a docker environment.  Disable the bazel sandbox using `--spawn_strategy=local` and it worked for me.

I'm no expert on docker so there may be a way to make that work, but in any case, your problem is in your bazel/docker configuration.

**Comment by cjds** [comment]
That did work. I'll close the ticket. Thanks for all the help. Really appreciate it
For future humans, the `local` strategy is what you want to prevent weird failure to look ups
```
local causes commands to be executed as local subprocesses.

```
